# Generated by Django 5.1.4 on 2024-12-08 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('default_total_score', models.IntegerField(default=100)),
                ('total_score', models.IntegerField(default=0)),
                ('total_problems', models.IntegerField(default=20)),
                ('correct_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=500)),
                ('score', models.IntegerField()),
                ('success', models.BooleanField(default=False)),
                ('order', models.IntegerField()),
                ('problem_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='main.problemset')),
            ],
        ),
    ]
